spring:
    application:
        name: XTR

application:
    dslPath: DSL

    ssl:
        certification:
        key:
        keystore-password: 123456

    client-data:
        member-class: GOV
        member-code: 70006317
        sybsystem-code: byrokratt

    security-server: https://out.test.x-tee.ee:443/
    xroad-instance: ee-test